/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class core_utils_matrix_MatrixOperations */

#ifndef _Included_core_utils_matrix_MatrixOperations
#define _Included_core_utils_matrix_MatrixOperations
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     core_utils_matrix_MatrixOperations
 * Method:    addMatrices
 * Signature: ([DII[DII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_core_utils_matrix_MatrixOperations_addMatrices
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jdoubleArray, jint, jint);

/*
 * Class:     core_utils_matrix_MatrixOperations
 * Method:    subtractMatrices
 * Signature: ([DII[DII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_core_utils_matrix_MatrixOperations_subtractMatrices
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jdoubleArray, jint, jint);

/*
 * Class:     core_utils_matrix_MatrixOperations
 * Method:    multiplyMatrices
 * Signature: ([DII[DII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_core_utils_matrix_MatrixOperations_multiplyMatrices
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jdoubleArray, jint, jint);

/*
 * Class:     core_utils_matrix_MatrixOperations
 * Method:    scalarMultiply
 * Signature: ([DIID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_core_utils_matrix_MatrixOperations_scalarMultiply
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jdouble);

/*
 * Class:     core_utils_matrix_MatrixOperations
 * Method:    transpose
 * Signature: ([DII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_core_utils_matrix_MatrixOperations_transpose
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     core_utils_matrix_MatrixOperations
 * Method:    determinant
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_core_utils_matrix_MatrixOperations_determinant
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     core_utils_matrix_MatrixOperations
 * Method:    inverse
 * Signature: ([DII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_core_utils_matrix_MatrixOperations_inverse
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     core_utils_matrix_MatrixOperations
 * Method:    trace
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_core_utils_matrix_MatrixOperations_trace
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     core_utils_matrix_MatrixOperations
 * Method:    rank
 * Signature: ([DII)I
 */
JNIEXPORT jint JNICALL Java_core_utils_matrix_MatrixOperations_rank
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     core_utils_matrix_MatrixOperations
 * Method:    isSymmetric
 * Signature: ([DII)Z
 */
JNIEXPORT jboolean JNICALL Java_core_utils_matrix_MatrixOperations_isSymmetric
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
